# Generated by Django 6.0 on 2026-01-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_product_created_at_alter_product_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["created_at", "category"],
                "permissions": [
                    ("can_unpublish_product", "Право отменять публикацию продукта"),
                    ("can_delete_product", "Право на удаление любого продукта"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("public", "Опубликовано"), ("unpublic", "Не опубликовано")],
                default="public",
                max_length=25,
                verbose_name="Статус публикации",
            ),
        ),
    ]
