# Generated by Django 6.0 on 2026-01-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_product_options_product_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("public", "Опубликовано"), ("unpublic", "Не опубликовано")],
                default="unpublic",
                max_length=25,
                verbose_name="Статус публикации",
            ),
        ),
    ]
